apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app.kubernetes.io/name: drogue-ajour
    app.kubernetes.io/instance: ajour
    app.kubernetes.io/component: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: drogue-ajour
      app.kubernetes.io/instance: ajour
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: drogue-ajour
        app.kubernetes.io/instance: ajour
        app.kubernetes.io/component: server
    spec:
      serviceAccountName: builder
      containers:
      - name: server
        image: ghcr.io/drogue-iot/drogue-ajour:latest
        imagePullPolicy: Always
        env:
          - name: RUST_LOG
            value: drogue_ajour=debug
          - name: OCI_REGISTRY_PREFIX
            valueFrom:
              secretKeyRef:
                key: prefix
                name: container-registry
          - name: OCI_REGISTRY_TOKEN
            valueFrom:
              secretKeyRef:
                key: token
                name: container-registry
          - name: DROGUE_TOKEN
            valueFrom:
              secretKeyRef:
                key: token
                name: drogue-config
          - name: DROGUE_USER
            valueFrom:
              secretKeyRef:
                key: user
                name: drogue-config
          - name: DROGUE_DEVICE_REGISTRY
            valueFrom:
              secretKeyRef:
                key: registry-url
                name: drogue-config
          - name: DROGUE_MQTT_INTEGRATION
            valueFrom:
              secretKeyRef:
                key: mqtt-integration
                name: drogue-config
          - name: MQTT_GROUP_ID
            value: firmware
          - name: HAWKBIT_ENABLE
            value: "true"
          - name: HAWKBIT_URL
            valueFrom:
              secretKeyRef:
                key: url
                name: hawkbit-config
          - name: HAWKBIT_GATEWAY_TOKEN
            valueFrom:
              secretKeyRef:
                key: gateway-token
                name: hawkbit-config
          - name: HAWKBIT_TENANT
            valueFrom:
              secretKeyRef:
                key: tenant
                name: hawkbit-config
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
