[workspace]
members = [
    "server",
    "protocol", 
]
resolver = "2"

[patch.crates-io]
drogue-client = { git = "https://github.com/drogue-iot/drogue-client.git", rev = "d69148b1678a6287b17ff38f25db0ef652f65cfd" }
