name: images
on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_publish:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Registry login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      
      - name: Build and push images
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
						ghcr.io/drogue-iot/drogue-ajour:latest
          push: ${{ github.ref == 'refs/heads/main' }}
