apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: firmware-build
spec:
  params:
    - default: .
      name: PROJECT_PATH
      description: Path to cargo project to build
      type: string
  steps:
    - command:
        - /bin/bash
        - '-c'
        - >-
          cp Dockerfile $(workspaces.input.path)/$(params.PROJECT_PATH) &&
          cd $(workspaces.input.path)/$(params.PROJECT_PATH) &&
          git rev-parse --short HEAD | tr -d '\n' > $(results.revision.path) &&
          REVISION=$(cat $(results.revision.path)) cargo objcopy --release -- -O binary firmware.bin &&
          REV=$(cat $(results.revision.path)) SZ=$(du -b firmware.bin | cut -f1) SHA=$(sha256sum firmware.bin) echo "{\"version\":\"${REV}\",\"size\":\"{SZ}\",\"checksum\":\"${SHA}\"}" > firmware.json
      image: 'docker.io/lulf/firmware-builder:latest'
      name: build
      resources: {}
  results:
    - name: revision
      description: Git revision
  workspaces:
    - description: Build directory
      mountPath: /workspace
      name: input
