apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: firmware-build
spec:
  params:
    - default: .
      name: PROJECT_PATH
      description: Path to cargo project to build
      type: string
    - default: ""
      name: CARGO_BUILD_ARGS
      description: Additional arguments to pass to cargo
      type: string
    - name: BUILDER_IMAGE
      description: Firmware builder image
      type: string
  steps:
    - command:
        - /bin/bash
        - '-c'
        - >-
          cp Dockerfile $(workspaces.input.path)/$(params.PROJECT_PATH) &&
          ./build.sh $(workspaces.input.path)/$(params.PROJECT_PATH) $(params.CARGO_BUILD_ARGS) &&
          cd $(workspaces.input.path)/$(params.PROJECT_PATH) &&
          git rev-parse --short HEAD | tr -d '\n' > $(results.revision.path)
      image: $(params.BUILDER_IMAGE)
      name: build
  results:
    - name: revision
      description: Git revision
  workspaces:
    - description: Build directory
      mountPath: /workspace
      name: input
