apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: firmware-build
spec:
  params:
    - default: .
      name: PROJECT_PATH
      description: Path to the project directory
      type: string
    - name: BUILD_ARGS
      default: []
      description: Additional arguments to pass to cargo
      type: array
    - name: BUILDER_IMAGE
      description: Firmware builder image
      type: string
  steps:
    - args: ["$(params.BUILD_ARGS[*])"]
      image: $(params.BUILDER_IMAGE)
      workingDir: $(workspaces.input.path)/$(params.PROJECT_PATH)
      name: build
  workspaces:
    - description: Build directory
      mountPath: /workspace
      name: input
