apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: firmware-bundle
spec:
  params:
    - default: .
      name: PROJECT_PATH
      description: Path to the project directory
      type: string
    - default: firmware.bin
      name: ARTIFACT_PATH
      description: Path to built artifact
      type: string
    - name: BUNDLER_IMAGE
      description: Bundler image
      type: string
  steps:
    - command:
        - /bin/bash
        - '-c'
        - >-
          cp Dockerfile $(workspaces.input.path)/$(params.PROJECT_PATH) &&
          ./bundle.sh $(workspaces.input.path)/$(params.PROJECT_PATH) $(params.ARTIFACT_PATH)
      image: $(params.BUNDLER_IMAGE)
      name: bundler
  workspaces:
    - description: Build directory
      mountPath: /workspace
      name: input
