apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: oci-firmware
spec:
  params:
    - description: Firmware repository
      name: GIT_REPO
      type: string
    - default: main
      description: Revision
      name: GIT_REVISION
      type: string
    - default: .
      name: PROJECT_PATH
      description: Path to project to build
      type: string
    - default: firmware.bin
      name: ARTIFACT_PATH
      description: Path to resulting artifact from build
      type: string
    - default: image-registry.openshift-image-registry.svc:5000/drogue-ajour
      description: Registry for image
      name: REGISTRY
      type: string
    - name: BUILDER_IMAGE
      description: Firmware builder image
      type: string
    - name: BUNDLER_IMAGE 
      description: Firmware bundler image
      type: string
      default: image-registry.openshift-image-registry.svc:5000/drogue-ajour/firmware-bundler:latest
    - description: Firmware image name
      name: IMAGE
      type: string
    - name: BUILD_ARGS
      type: array
      description: Additional arguments to pass to cargo
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: build
    - name: firmware-build
      params:
        - name: PROJECT_PATH
          value: $(params.PROJECT_PATH)
        - name: BUILDER_IMAGE
          value: $(params.BUILDER_IMAGE)
        - name: BUILD_ARGS
          value: ["$(params.BUILD_ARGS[*])"]
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: firmware-build
      workspaces:
        - name: input
          workspace: build
    - name: firmware-publish
      params:
        - name: IMAGE
          value: $(params.REGISTRY)/$(params.IMAGE)
        - name: ARTIFACT_PATH
          value: $(params.ARTIFACT_PATH)
        - name: CONTEXT
          value: $(workspaces.source.path)/$(params.PROJECT_PATH)
      runAfter:
        - firmware-build
      taskRef:
        kind: Task
        name: oras-push
      workspaces:
        - name: source
          workspace: build
  workspaces:
    - name: build
