apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: oci-firmware
spec:
  params:
    - description: Firmware repository
      name: GIT_REPO
      type: string
    - default: main
      description: Revision
      name: GIT_REVISION
      type: string
    - default: image-registry.openshift-image-registry.svc:5000/
      description: Firmware image name
      name: REGISTRY
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: build
    - name: firmware-build
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: firmware-build
      workspaces:
        - name: input
          workspace: build
    - name: firmware-deploy
      params:
        - name: IMAGE
          value: $(params.REGISTRY)/$(params.FIRMWARE_NAME):$(tasks.firmware-build.results.revision)
        - name: DOCKERFILE
          value: $(workspaces.source.path)/Dockerfile
        - name: CONTEXT
          value: $(workspaces.source.path)
        - name: BUILD_EXTRA_ARGS
          value: --label io.drogue.metadata="`cat $(workspaces.source.path)/firmware/application/firmware.json`"
      runAfter:
        - firmware-build
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: build
    - name: registry-update
      params:
        - name: IMAGE
          value: $(params.FIRMWARE_NAME)
        - name: REVISION
          value: $(tasks.firmware-build.results.revision)
      runAfter:
        - firmware-deploy
      taskRef:
        kind: Task
        name: registry-update
  workspaces:
    - name: build
