apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: oci-firmware
spec:
  params:
    - description: Firmware repository
      name: GIT_REPO
      type: string
    - default: main
      description: Revision
      name: GIT_REVISION
      type: string
    - default: .
      name: PROJECT_PATH
      description: Path to cargo project to build
      type: string
    - default: image-registry.openshift-image-registry.svc:5000/drogue-ajour
      description: Registry for image
      name: REGISTRY
      type: string
    - name: BUILDER_IMAGE
      description: Firmware builder image
      type: string
      default: image-registry.openshift-image-registry.svc:5000/drogue-ajour/firmware-builder:latest
    - description: Firmware image name
      name: IMAGE
      type: string
    - default: ""
      name: CARGO_BUILD_ARGS
      description: Additional arguments to pass to cargo
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: build
    - name: firmware-build
      params:
        - name: PROJECT_PATH
          value: $(params.PROJECT_PATH)
        - name: BUILDER_IMAGE
          value: $(params.BUILDER_IMAGE)
        - name: CARGO_BUILD_ARGS
          value: $(params.CARGO_BUILD_ARGS)
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: firmware-build
      workspaces:
        - name: input
          workspace: build
    - name: firmware-publish
      params:
        - name: IMAGE
          #value: $(params.REGISTRY)/$(params.IMAGE):$(tasks.firmware-build.results.revision)
          value: $(params.REGISTRY)/$(params.IMAGE):$(params.GIT_REVISION)
        - name: DOCKERFILE
          value: $(workspaces.source.path)/$(params.PROJECT_PATH)/Dockerfile
        - name: CONTEXT
          value: $(workspaces.source.path)/$(params.PROJECT_PATH)
        - name: BUILD_EXTRA_ARGS
          value: --label io.drogue.metadata="`cat $(workspaces.source.path)/$(params.PROJECT_PATH)/firmware.json`"
      runAfter:
        - firmware-build
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: build
  workspaces:
    - name: build
