apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: registry-update
spec:
  params:
    - name: REGISTRY_VOLUME
      type: string
      description: Name of registry volume
      default: registry
    - name: IMAGE
      type: string
      description: Name of image to update entry for
    - name: REVISION
      type: string
      description: Revision of the image to mark as latest
  steps:
    - command:
        - /bin/bash
        - '-c'
        - >-
          mkdir -p /registry/$(params.IMAGE) &&
          echo -n $(params.REVISION) > /registry/$(params.IMAGE)/latest
      image: ubuntu
      name: update-registry
      volumeMounts:
        - name: registry-index
          mountPath: /registry
  volumes:
    - name: registry-index
      persistentVolumeClaim:
        claimName: "$(params.REGISTRY_VOLUME)"
