apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: oci-firmware-run
spec:
  params:
  - name: GIT_REPO
    value: https://github.com/drogue-iot/burrboard
  - name: GIT_REVISION
    value: main
  - name: FIRMWARE_IMAGE
    value: image-registry.openshift-image-registry.svc:5000/drogue-firmware/burrboard
  pipelineRef:
    name: oci-firmware
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
  - name: build
    persistentVolumeClaim:
      claimName: build-workspace
